numero = int(input('Digite um número para saber sua tabuada.'))
print('{} x 1 é igual a {}'.format(numero,numero*1))
print('{} x 2 é igual a {}'.format(numero,numero*2))
print('{} x 3 é igual a {}'.format(numero,numero*3))
print('{} x 4 é igual a {}'.format(numero,numero*4))
print('{} x 5 é igual a {}'.format(numero,numero*5))
print('{} x 6 é igual a {}'.format(numero,numero*6))
print('{} x 7 é igual a {}'.format(numero,numero*7))
print('{} x 8 é igual a {}'.format(numero,numero*8))
print('{} x 9 é igual a {}'.format(numero,numero*9))
print('{} x 10 é igual a {}'.format(numero,numero*10))